### ISSUE TITLE
Import SVG paths

### ISSUE THREAD

**Issue by korpx** [blinkenlight/GCAM#12]
Totally new to GCAM. How do I use "Import SVG Paths"? Importing thread_cutter.svg doesn't seem to do much and I find no info in the wiki on how to use it.

![image](https://github.com/blinkenlight/GCAM/assets/1850308/c1bec91b-27db-4426-91fa-de22687f8585)

**Comment by blinkenlight** [comment]
No idea what's going on there. Just downloaded the latest release, clicked "new project", "apply", "import SVG paths", "thread_cutter.svg" and it worked fine for me. What OS are you on?

**Comment by korpx** [comment]
Windows 10 22H2 64bit.
I will give it a try on other hardware tomorrow.

**Comment by korpx** [comment]
Tried it again on the same machine and now it works! Closing the issue.
