### ISSUE TITLE
Problems with parameter dot

### ISSUE THREAD

**Issue by easy2003** [blinkenlight/GCAM#4]
Hello. In the program I have a problem. In the parameter settings, I can not set points special nufkommas. It records commas as points in the gcode. I live in Germany

**Comment by blinkenlight** [comment]
I'm afraid I don't quite understand. Which parameters, a specific one or any in general? What exactly are you trying to do with points or commas? Can you please rephrase / elaborate?

**Comment by easy2003** [comment]
at all parameter in the gcode. I must convert all , to . in the gcode file.

**Comment by blinkenlight** [comment]
Oh, I see - the German regional settings that use a comma as decimal separator instead of the English decimal point are also getting used to output the G-code file, which should always use a decimal point. Yeah, that's indeed a bug. Thanks.
